spring:
  application:
    name: config-server
#  profiles:
#    active: native

  cloud:
    config:
      server:
        git:
          uri: F:/config-server-git
          default-label: master  
#          username: priyaghadge99
          


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
     defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
     
management:
  tracing:
    sampling:
      probability: 1.0        
    
server:
  port: 8888    
    
      