spring:
  application:
    name: config-server
#  profiles:
#    active: native

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/priyaghadge99/config-server-git}
          default-label: main  
          username: ${USERNAME:priyaghadge99}
          password: ${PASSWORD:priyaghadge1}
          skipSslValidation: true
          force-pull: true
      enabled: true
      uri: http://localhost:8888
      label: main
          
          


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
     defaultZone: ${EUREKASERVER_URI :http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true
     
management:
  tracing:
    sampling:
      probability: 1.0        
  endpoint:
    health:
      show-details: never
    
server:
  port: 8888    
  
      