spring:
  application:
    name: config-server
  profiles:
    active: native
server:
  port: 8888 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
     defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
     
     
    
    
    
      